options:
  app_name:
    type: string
    description: |
      Name of the application.
    default: "Canonical CLA"
  app_url:
    type: string
    description: |
      URL of the application.
  rate_limit_whitelist:
    type: string
    description: |
      Comma-separated list of IP addresses to exclude from rate limiting (e.g. '["127.0.0.1", "localhost"]').
    default: '["127.0.0.1", "localhost"]'
  secret_key:
    type: secret
    description: |
      Secret key used to encrypt cookie sessions.
  github_oauth:
    type: secret
    description: |
      GitHub OAuth configuration (client ID and secret).
  smtp:
    type: string
    description: |
      SMTP server configuration (host, port, username, password).
