options:
  app_name:
    type: string
    description: |
      Name of the application.
    default: "Canonical CLA"
  app_url:
    type: string
    description: |
      URL of the application.
  environment:
    type: string
    description: |
      Environment in which the application is running.
    default: "development"
  sentry_dsn:
    type: string
    description: |
      Sentry DSN (optional).
  smtp_legal_contact_email:
    type: string
    description: |
      Legal contact email address.
    default: "Canonical's Legal Team <legal@canonical.com>"
  rate_limit_whitelist:
    type: string
    description: |
      Comma-separated list of IP addresses to exclude from rate limiting (e.g. '["127.0.0.1", "localhost"]').
    default: '["127.0.0.1", "localhost"]'
  secret_key:
    type: secret
    description: |
      Secret key used to encrypt cookie sessions.
  github_oauth:
    type: secret
    description: |
      GitHub OAuth configuration (client ID and secret).
  smtp:
    type: secret
    description: |
      SMTP server configuration (host, port, username, password).
  database:
    type: secret
    description: |
      Database configuration (host, port, name, username, password), this overrides the database relation.
