options:
  secret_key:
    type: secret
    description: |
      Secret key used to encrypt cookie sessions.
  github_oauth:
    type: secret
    description: |
      GitHub OAuth configuration (client ID and secret).
